name: Build and Deploy Code
on: [push, pull_request]
# env: # if we want to define global env variables (common to different jobs)
#   DATABASE_HOSTNAME: localhost
jobs:
  job1:
    environment:
      name: testing
    env: #setting environement variables
      DATABASE_HOSTNAME: localhost #${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: 5432 #${{secrets.DATABASE_PORT}}
      DATABASE_USERNAME: postgres #${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: password123 #${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: fastapi #${{secrets.DATABASE_NAME}}
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7 #${{secrets.SECRET_KEY}}
      ALGORITHM: HS256 #${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: 60 #${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password123 #${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: fastapi_test #${{secrets.DATABASE_NAME}}_test
        ports:
        - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python version 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test RestApi with pytest
        run: |
          pip install pytest
          pytest
  
